import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './global.css';
import styles from './layout.module.scss';

import StoreProvider from './StoreProvider';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Dogsterest',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<StoreProvider>
			<html lang="en">
				<body className={inter.className}>
					<Header />
					<main className={styles.mainContainer}>
						<div className={styles.cardContainer}>{children}</div>
					</main>
				</body>
			</html>
		</StoreProvider>
	);
}
